### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by bunnylushington** [samschloegel/qlab-scripts#1]
Hi Sam -- As requested, I'd like to let you know that I have found a few of your scripts **extremely** useful.  I appreciate you not only sharing the scripts but also the effort you made documenting what they do (and why they're useful!).  Your libraries are also excellent examples of how to program in Applescript.  (I'm a professional computer programmer and still Applescript remains fairly opaque; examples are clutch.)

Further, I've assembled a [QLab template](https://github.com/bunnylushington/qlab-xkeys-setup) that includes some of your work.  I've attributed you in two places: in the documentation and in the Notes section of the relevant script cues.  I've included a link to your GitHub repo in both places.  If you have any concerns about how you're attributed or the inclusion of your code in my template, please let me know.  Thanks!

**Comment by samschloegel** [comment]
Really glad to hear you found these helpful!
Including a link to this repo either in the cue notes or in the script itself sounds good to me.

Thanks!
Sam
